os:
  - linux
sudo: false
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
before_script:
  - git clone https://github.com/flutter/flutter.git -b beta
  - ./flutter/bin/flutter doctor
jobs:
  - name: test app
    script: cd home_insurance_app; ../flutter/bin/flutter test;
  - name: format app
    script: ./flutter/bin/flutter format -n --set-exit-if-changed home_insurance_app/lib/* home_insurance_app/test/*
  - name: test sdk
    script: cd sdk; ../flutter/bin/flutter test;
  - name: format sdk
    script: ./flutter/bin/flutter format -n --set-exit-if-changed sdk/lib/* sdk/test/*
cache:
  directories:
    - $HOME/.pub-cache
